### ISSUE TITLE
Create an animation for the edit mode button

### ISSUE THREAD

**Issue by jacob-and-nathan** [jacob-and-nathan/SoftwarePlanner#20]
When you click on a text area, or input when you AREN'T in edit mode, it would be nice to have some sort of animation to show that you need to GO to edit mode. Maybe the edit mode button could shake?

**Comment by carlosrrod** [comment]
Sure, we could add an event listener on the card itself and have it check for a class, something like `.card-edit-active` and if the card is clicked and this class is **not** applied, it will cause the **edit** button to shake. Clicking the **edit** button will add the class to the card, hitting the **confirm** button will remove it. 

Shouldn't be too hard to implement. Assign this issue to me if you'd like me to work on it.

**Comment by jacob-and-nathan** [comment]
I have assigned you to this issue - sounds great!
