### ISSUE TITLE
Continue programming the main page.

### ISSUE THREAD

**Issue by jacob-and-nathan** [jacob-and-nathan/SoftwarePlanner#6]
Using HTML, CSS and JAVASCRIPT. 
(The actual HOMEPAGE will be done later)
Look at the image called 'MainPagePrototype' in the designfiles folder in the repo.

**Comment by carlosrrod** [comment]
Need to clarify, you want to re-create the MainPagePrototype in code using HTML and CSS?

**Comment by jacob-and-nathan** [comment]
Yes - the MainPagePrototype.png file in the DesignsAndPlanning folder. Sorry, the description is quite unclear. I chose to use HTML and CSS (and JAVASCRIPT) because I don't have much experience with any other frameworks, etc.
If you want to use another framework, you're welcome to.

**Comment by carlosrrod** [comment]
I went ahead and created a pull request. Take a look at it, I wanted your approval before continuing with the Javascript functionality.

**Comment by carlosrrod** [comment]
I'll begin working on the Javascript. If you want to make changes to the design on the website just let me know so I can update the CSS accordingly.

**Comment by jacob-and-nathan** [comment]
Great, thanks!

**Comment by jacob-and-nathan** [comment]
I have merged the Pull Request - thanks very much! I like the animations - they are simple but very cool!

**Comment by carlosrrod** [comment]
Thanks, will continue working on the Javascript so users can add more cards.

**Comment by carlosrrod** [comment]
Good work adding those extra shadows and the confirm alert! I noticed that the placement of the confirm button is a little too far to the left, it's overlaying with the input. Just edit the CSS for the confirm button:

`.project-card-edit-confirm-btn` or you can resize the size of the input. Whichever you feel is best.

**Comment by jacob-and-nathan** [comment]
Yes, I decided to resize the input. A quick question: At first you could just edit the body and title of the project card without going into edit mode, but it has changed, and now you need to press the button on the top-right of the card to edit the text.
I think we should maybe put it back to what it was before, because much easier and quicker for the user. What do you think?

**Comment by carlosrrod** [comment]
Sorry for the delayed response. Sure we can let the user edit the card as soon as its created. And then after that, if they'd like to edit again they'd have to click on the Edit button. Or we could just keep the card editable all the time if that's what you want.

**Comment by carlosrrod** [comment]
I went ahead and fixed the Javascript to allow the card to edited from the start. Also, check line 28 in app.js. `projectCardDeleteBtn.innerText = '-';` This overlays with the delete button icon.

**Comment by jacob-and-nathan** [comment]
Don't worry about the delayed response - we are in different time zones anyway!
I have changed some of the styling, the next thing to work on would probably be a '+' button inside each card (like there was in your first pull request) where you can add another text block or an image.

Once that is completed, we can work or adding the ability to add multiple cards.

**Comment by jacob-and-nathan** [comment]
Just to let you know, to keep things organised, I have closed this issue and moved it to a different issue. Also, I have already PARTLY completed the thing I was talking about in the least comment.
